managed-by: giantswarm

name: loadtest-app
namespace: default

replicaCount: 1

image:
  repository: stormforger/testapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  paths:
    - "/"
  hosts:
    - testapp.ss863.k8s.ginger.eu-west-1.aws.gigantic.io

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  - name: DISABLE_TLS
    value: "true"
