name: loadtest-app

replicaCount: 1

image:
  repository: stormforger/testapp
  tag: "latest@sha256:0c7c3e825277bbb1b7f1ba56bdc1fda8e08042a94169bb75966f244e94e46300"
  pullPolicy: Always

userID: 1000
groupID: 1000

service:
  port: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  paths:
    - "/"
  hosts: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  - name: DISABLE_TLS
    value: "true"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

nodeAffinity:
  enabled: false
  selector: {}
