version: 2.1
orbs:
  architect: giantswarm/architect@5.11.5

workflows:
  version: 2
  build:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: push-to-default-app-catalog
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: loadtest-app
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
